import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 10, y = 5 }

[font]
normal = { family = "MonoLisa", style = "Regular" }
bold = { family = "MonoLisa", style = "Bold" }
italic = { family = "MonoLisa", style = "Regular Italic" }
bold_italic = { family = "MonoLisa", style = "Bold Italic" }
size = 17
# this is basically the line offset
offset = { x = 1, y = 20 }
glyph_offset = { x = 0, y = 10 }

[keyboard]
bindings = [
    # ctrl-6 doesn't work without this (for vim buffer switching)
    { key = "Key6", mods = "Control", chars = "\u001e" }
]
