# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: !!null delta -s
# Aliases allow you to create nicknames for gh commands
aliases:
    # prompt to check out a PR number or use the passed in number
    co: >-
        !id="$(if [ -z "$1" ]; then gh pr list -L100 | fzf --no-multi | cut -f1; else echo $1; fi)";
        [ -n "$id" ] && gh pr checkout "$id"
    cr: pr create
    crd: pr create -d
    v: pr view -w
    b: repo view -w
    al: alias list
    # prompt to view a PR number or use the passed in number
    vv: >-
        !id="$(if [ -z "$1" ]; then gh pr list -L100 | fzf --no-multi | cut -f1; else echo $1; fi)";
        [ -n "$id" ] && gh v "$id"
