---
language: generic
os: osx
osx_image: xcode8.2

before_install:
  # update homebrew
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update ; fi
  # create temporary log file
  - idempotence=`mktemp`

install:
  - brew install ansible

script:
  # check syntax
  - ansible-playbook macbook.yml --syntax-check
  # run playbook
  # NOTE: ssh task won't work because it prompts for password
  # NOTE: `user` dict is not defined in this repo so pass it with playbook
  - ansible-playbook macbook.yml --skip-tags ssh -e "{'user':{'name':'{$USER}','email':'${USER}@${TRAVIS_OS_NAME}.com'}}"
  # check idempotence
  - ansible-playbook macbook.yml --skip-tags ssh -e "{'user':{'name':'{$USER}','email':'${USER}@${TRAVIS_OS_NAME}.com'}}" | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
