---
language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      language: python
    - os: osx
      osx_image: xcode8.2

before_install:
  # update homebrew
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update ; fi
  # create temporary log file
  - idempotence=`mktemp`

install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install ansible ; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo pip install ansible ; fi

script:
  # check syntax
  - ansible-playbook dotfiles.yml --syntax-check
  # run playbook
  # NOTE: ssh task won't work because it prompts for password
  # NOTE: `user` dict is not defined in this repo so pass it with playbook
  - ansible-playbook dotfiles.yml --skip-tags ssh -e "{'user':{'name':'${USER}','email':'${USER}@${TRAVIS_OS_NAME}.com'}}"
  # check idempotence
  - ansible-playbook dotfiles.yml --skip-tags ssh -e "{'user':{'name':'${USER}','email':'${USER}@${TRAVIS_OS_NAME}.com'}}" | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
