enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders'
]
exec-on-workspace-change = [
    '/bin/bash', '-c', '/opt/homebrew/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[mode.main.binding]
alt-enter = 'exec-and-forget open -a /Applications/kitty.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-backtick = 'workspace-back-and-forth'
alt-tab = 'workspace next --wrap-around'
alt-shift-tab = 'workspace prev --wrap-around'

alt-b = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 01'
alt-2 = 'workspace 02'
alt-3 = 'workspace 03'
alt-4 = 'workspace 04'
alt-5 = 'workspace 05'
alt-6 = 'workspace 06'
alt-7 = 'workspace 07'
alt-8 = 'workspace 08'
alt-9 = 'workspace 09'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 01'
alt-shift-2 = 'move-node-to-workspace 02'
alt-shift-3 = 'move-node-to-workspace 03'
alt-shift-4 = 'move-node-to-workspace 04'
alt-shift-5 = 'move-node-to-workspace 05'
alt-shift-6 = 'move-node-to-workspace 06'
alt-shift-7 = 'move-node-to-workspace 07'
alt-shift-8 = 'move-node-to-workspace 08'
alt-shift-9 = 'move-node-to-workspace 09'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = [{ monitor.'^built-in retina display$' = 4 }, 34]
outer.right = 4

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Jarryd (Buildkite)'
run = 'move-node-to-workspace 01'
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 02'
[[on-window-detected]]
if.app-id = 'com.mimestream.Mimestream'
run = 'move-node-to-workspace 03'
[[on-window-detected]]
if.app-id = 'com.linear'
run = 'move-node-to-workspace 04'
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 06'
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Jarryd'
run = 'move-node-to-workspace 07'
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 09'
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = 'layout floating'
