#! /usr/bin/env ansible-playbook --ask-vault-pass

## ----------------------------------------------------
## Common ansible playbook for setting up a new machine
## ----------------------------------------------------
---
- name: common tasks
  hosts: localhost

  # include all variables first to allow overriding
  vars_files:
    - vars/atom.yml
    - vars/dotfiles.yml

  tasks:
    ## -----------------------------------------------
    ## Include vars_file for overriding default values
    ## -----------------------------------------------
    - name: include override vars_file (if it exists)
      tags: always
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - ../vars/override.yml
          skip: true # don't error if not found

    ## --------------------------
    ## Include modular task files
    ## --------------------------
    - include: tasks/atom.yml

    - include: tasks/dotfiles.yml

    - include: tasks/ssh.yml

    - include: tasks/vim.yml
