#!/usr/bin/env ansible-playbook

## ---------------------------------------------
## Ansible playbook for setting up a new machine
## ---------------------------------------------
---
- name: Configure a new machine
  hosts: localhost

  handlers:
    - name: restart dock
      command: killall Dock
      listen: restart mac services
      when: ansible_distribution == 'MacOSX'

    - name: restart mac services
      command: killall {{ item }}
      with_items:
        - Finder
        - Safari
        - SystemUIServer
        - cfprefsd
      when: ansible_distribution == 'MacOSX'

  pre_tasks:
    - name: include variables
      tags: always
      include_vars:
        dir: vars

  tasks:
    ## ------------------------
    ## Run macOS specific tasks
    ## ------------------------
    - include: tasks/macbook.yml
      tags: osx
      when: ansible_distribution == 'MacOSX'

    ## -------------------------
    ## Run Ubuntu specific tasks
    ## -------------------------
    - include: tasks/ubuntu.yml
      tags: ubuntu
      become: true
      when: ansible_distribution == 'Ubuntu'

    ## --------------------------
    ## Include common task files
    ## --------------------------
    - include: tasks/atom.yml
      tags:
        - common
        - atom

    - include: tasks/dotfiles.yml
      tags:
        - common
        - dotfiles

    - include: tasks/python.yml
      tags:
        - common
        - python

    - include: tasks/ssh.yml
      tags:
        - common
        - ssh

    - include: tasks/vim.yml
      tags:
        - common
        - vim
