#!/usr/bin/env ansible-playbook

## -------------------------------------------------------------
## Ansible playbook for setting up a new machine
##
## This handles the 2 platforms that I use; Arch Linux and MacOS
## -------------------------------------------------------------

---
## -------------------------
## Arch Linux specific tasks
## -------------------------
- name: Configure Arch Linux
  hosts: archlinux
  tags: archlinux
  gather_facts: no
  become: yes
  tasks:
    - import_tasks: tasks/archlinux.yml


## --------------------
## MacOS specific tasks
## --------------------
- name: Configure MacOS
  hosts: macos
  tags: macos
  gather_facts: no
  handlers:
    - name: restart dock
      command: killall Dock
      listen: restart mac services
    - name: restart mac services
      command: killall {{ item }}
      loop:
        - Finder
        - Safari
        - SystemUIServer
        - cfprefsd
  tasks:
    - import_tasks: tasks/macbook.yml


## -----------------------
## Platform agnostic tasks
## -----------------------
- name: Configure common stuff
  hosts: all
  tags: common
  tasks:
    - name: gather facts
      tags: dotfiles
      setup:
    - import_tasks: tasks/dotfiles.yml
      tags: dotfiles
    - import_tasks: tasks/ssh.yml
      tags: ssh
    - import_tasks: tasks/git.yml
      tags: git
    - import_tasks: tasks/vim.yml
      tags: vim
