#!/usr/bin/env ansible-playbook

## -------------------------------------------------------------------------------
## Ansible playbook for setting up a new machine
##
## This handles the 3 platforms that I generally use; Arch Linux, Ubuntu and MacOS
## -------------------------------------------------------------------------------

---
## -------------------------
## Arch Linux specific tasks
## -------------------------
- name: Configure Arch Linux
  hosts: archlinux
  tags: archlinux
  become: true
  tasks:
    - include: tasks/archlinux.yml
      static: yes


## ---------------------
## Ubuntu specific tasks
## ---------------------
- name: Configure Ubuntu
  hosts: ubuntu
  tags: ubuntu
  become: true
  tasks:
    - include: tasks/ubuntu.yml
      static: yes


## --------------------
## MacOS specific tasks
## --------------------
- name: Configure MacOS
  hosts: macos
  tags: macos
  handlers:
    - name: restart dock
      command: killall Dock
      listen: restart mac services
    - name: restart mac services
      command: killall {{ item }}
      with_items:
        - Finder
        - Safari
        - SystemUIServer
        - cfprefsd
  tasks:
    - include: tasks/macbook.yml
      static: yes


## -----------------------
## Platform agnostic tasks
## -----------------------
- name: Configure common stuff
  hosts: all
  tags: common
  tasks:
    - include: tasks/atom.yml
      static: yes
      tags: atom
    - include: tasks/dotfiles.yml
      static: yes
      tags: dotfiles
    - include: tasks/python.yml
      static: yes
      tags: python
    - include: tasks/ssh.yml
      static: yes
      tags: ssh
    - include: tasks/vim.yml
      static: yes
      tags: vim
