#! /usr/bin/env ansible-playbook --ask-vault-pass

## ---------------------------------------------
## Ansible playbook for setting up a new machine
## ---------------------------------------------
---
- name: Configure a new machine
  hosts: localhost

  # include all variables first to allow overriding
  vars_files:
    - vars/atom.yml
    - vars/dotfiles.yml
    - vars/python.yml

  handlers:
    - name: restart dock
      command: killall Dock
      listen: restart mac services
      when: ansible_distribution == 'MacOSX'

    - name: restart mac services
      command: killall {{ item }}
      with_items:
        - Finder
        - Safari
        - SystemUIServer
        - cfprefsd
      when: ansible_distribution == 'MacOSX'

  tasks:
    ## ------------------------
    ## Run macOS specific tasks
    ## ------------------------
    - include: tasks/macbook.yml
      tags: osx
      when: ansible_distribution == 'MacOSX'

    ## -------------------------
    ## Run Ubuntu specific tasks
    ## -------------------------
    - include: tasks/ubuntu.yml
      tags: ubuntu
      become: true
      when: ansible_distribution == 'Ubuntu'

    ## -----------------------------------------------
    ## Include vars_file for overriding default values
    ## -----------------------------------------------
    - name: include override vars (if it exists)
      tags: always
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - override.yml
          skip: true # don't error if not found

    ## --------------------------
    ## Include common task files
    ## --------------------------
    - include: tasks/atom.yml
      tags: common

    - include: tasks/dotfiles.yml
      tags: common

    - include: tasks/python.yml
      tags: common

    - include: tasks/ssh.yml
      tags: common

    - include: tasks/vim.yml
      tags: common
