---
## ----------------
## Install packages
## ----------------
- name: install packages with pacman
  pacman:
    pkg: "{{ pacman_packages }}"
    state: present

# TODO: how to do aur/yaourt packages? create module or use shell/command module

- name: start/enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ system_services }}"

- name: start/enable user services
  become: no
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop: "{{ user_services }}"
  failed_when: no # TODO: this fails on very first run because config files arent installed yet

- name: ignore pressing the power button
  ini_file:
    path: /etc/systemd/logind.conf
    section: Login
    option: HandlePowerKey
    value: ignore
    state: present
    backup: yes

- name: ignore some pacman packages
  ini_file:
    path: /etc/pacman.conf
    section: options
    option: IgnorePkg
    value: >
      iproute2
      minikube
      python
      terraform
    state: present
    backup: yes
