---
## ----------------
## Install packages
## ----------------
- name: install packages with pacman
  pacman:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ pacman_packages }}"

# TODO: how to do aur/yaourt packages? create module or use shell/command module

- name: start/enable system services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ system_services }}"

- name: start/enable user services
  become: no
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    user: yes
  with_items: "{{ user_services }}"
  failed_when: no # this fails on very first run because config files arent installed yet
