---
## ---------------------------
## Move in configuration files
## ---------------------------
- name: find dotfiles to link to ~
  find:
    paths: files/home/
    recurse: yes
    excludes: "{{ dotfile_blacklist | default(omit) }}"
  register: home_files

- name: find dotfiles to link to /etc
  find:
    paths: files/etc/
    recurse: yes
    excludes: "{{ dotfile_blacklist | default(omit) }}"
  register: etc_files

- name: find directories to create
  find:
    file_type: directory
    paths: files/home/
    recurse: yes
  register: home_dirs

- name: ensure directories exist
  file:
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files/home') }}"
    state: directory
  loop: "{{ home_dirs.files }}"
  loop_control:
    label: "{{ item.path }}"
  # if a blacklist is defined, use it, otherwise create all directories
  when: directory_blacklist is not defined or item.path is not search(directory_blacklist | join('|'))

- name: link dotfiles to home directory
  file:
    src: "{{ item.path | realpath }}"
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files/home') }}"
    state: link
  loop: "{{ home_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.path | splitext | last != '.j2'

- name: import dotfile templates to home directory
  template:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files/home') | splitext | first }}"
    backup: yes
    mode: "{{ item.mode }}"
  loop: "{{ home_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.path | splitext | last == '.j2'

- name: link dotfiles to etc directory
  become: yes
  file:
    src: "{{ item.path | realpath }}"
    dest: "/etc/{{ item.path | relpath('files/etc') }}"
    state: link
  loop: "{{ etc_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.path | splitext | last != '.j2'

- name: import dotfile templates to etc directory
  become: yes
  template:
    src: "{{ item.path }}"
    dest: "/etc/{{ item.path | relpath('files/etc') | splitext | first }}"
    backup: yes
  loop: "{{ etc_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.path | splitext | last == '.j2'

- name: link system files
  become: yes
  file:
    src: "{{ item.value }}"
    dest: "{{ item.key }}"
    state: link
    force: yes
  loop: "{{ symlinks | dict2items }}"
  when: ansible_distribution != 'MacOSX'

- name: ensure directories exist
  tags: testing
  file:
    dest: "{{ item.dest | dirname }}"
    state: directory
  loop: "{{ download_files }}"
  loop_control:
    label: "{{ item.dest | dirname }}"

- name: download files
  tags: testing
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop: "{{ download_files }}"
  loop_control:
    label: "{{ item.dest }}"
