---
## -------------------
## Configuration files
## -------------------
- name: find dotfiles to link
  find:
    paths: files/
    recurse: yes
  register: files

- name: find templates to import
  find:
    paths: templates/
    recurse: yes
  register: templates

- name: find directories to create
  find:
    file_type: directory
    paths:
      - files/
      - templates/
    recurse: yes
  register: dirs

- name: ensure directories exist
  file:
    dest: "{{ ansible_user_dir }}/.{{ item.path | regex_replace('^(templates|files)/', '') }}"
    state: directory
  with_items: "{{ dirs.files }}"

- name: link dotfiles to home directory
  file:
    src: "{{ item.path | realpath }}"
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files') }}"
    state: link
  with_items: "{{ files.files }}"

- name: import dotfile templates to home directory
  template:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/\
      .{{ item.path | relpath('templates') | splitext | first }}"
    backup: yes
  with_items: "{{ templates.files }}"
