---
## -------------------
## Configuration files
## -------------------
- name: include AWS credentials
  include_vars: ../vars/vault/aws_credentials.yml
  tags: dotfiles

- name: find dotfiles to link
  tags: dotfiles
  find:
    paths: files/
    recurse: yes
  register: files

- name: find templates to import
  tags: dotfiles
  find:
    paths: templates/
    recurse: yes
  register: templates

- name: link dotfiles to home directory
  tags: dotfiles
  file:
    src: "{{ item.path | realpath }}"
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files') }}"
    state: link
  with_items: "{{ files.files }}"

- name: import dotfile templates to home directory
  tags: dotfiles
  template:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/\
      .{{ item.path | relpath('templates') | splitext | first }}"
    backup: yes
  with_items: "{{ templates.files }}"
