---
## ---------------------------
## Move in configuration files
## ---------------------------
- name: find dotfiles to link
  find:
    paths: files/home/
    recurse: yes
  register: home_files

- name: find templates to import
  find:
    paths: templates/home/
    recurse: yes
  register: home_templates

- name: find directories to create
  find:
    file_type: directory
    paths:
      - files/home/
      - templates/home/
    recurse: yes
  register: home_dirs

- name: ensure directories exist
  file:
    dest: "{{ ansible_user_dir }}/.{{ item.path | regex_replace('^(templates|files)/home/', '') }}"
    state: directory
  with_items: "{{ home_dirs.files }}"

- name: link dotfiles to home directory
  file:
    src: "{{ item.path | realpath }}"
    dest: "{{ ansible_user_dir }}/.{{ item.path | relpath('files/home') }}"
    state: link
  with_items: "{{ home_files.files }}"

- name: import dotfile templates to home directory
  template:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir }}/\
      .{{ item.path | relpath('templates/home') | splitext | first }}"
    backup: yes
  with_items: "{{ home_templates.files }}"
