---
## --------------------------
## Clone any custom git repos
## --------------------------
- name: clone custom git repos
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
    update: no
  loop: "{{ git_repos | flatten }}"
