---
## ----------------------
## Homebrew related tasks
## ----------------------
- name: install homebrew taps
  tags: brew
  homebrew_tap:
    tap: "{{ item }}"
  loop: "{{ homebrew_taps }}"

- name: install mac apps
  tags: brew
  homebrew_cask:
    cask: "{{ item }}"
  loop: "{{ homebrew_casks }}"

- name: install mac packages
  tags: brew
  homebrew:
    name: "{{ homebrew_formulae }}"


## ----------
## Dock items
## ----------
- name: remove unnecessary dock items
  tags: dock
  command: dockutil --remove "{{ item }}" --no-restart
  with_lines: dockutil --list | cut -f 1
  when: >
    item not in (dock_apps + dock_dirs) | map(attribute='name') | map('basename') | map('splitext') | map('first')
    | list
  notify: restart dock

- name: add/rearrange dock items
  tags: dock
  shell: >
    [ "`dockutil --find '{{ item.name | basename | splitext | first }}' | \
      sed -n 's/.*slot \\([[:digit:]]*\\).*/\\1/p'`" -eq {% if index >= (dock_apps | length) %} \
        {{ 1 + index - dock_apps | length }} \
        {% else %} \
        {{ index + 1 }} \
        {% endif %} ] 2> /dev/null || \
    ( \
      dockutil --find "{{ item.name | basename | splitext | first }}" > /dev/null && \
      dockutil --move "{{ item.name | basename | splitext | first }}" \
        --position {% if index >= (dock_apps | length) %} \
        {{ 1 + index - dock_apps | length }} \
        {% else %} \
        {{ index + 1 }} \
        {% endif %} \
        --no-restart {{ item.options | default() }} && \
      echo changed \
    ) || \
    ( \
      dockutil --add "{{ item.name }}" \
        --position {% if index >= (dock_apps | length) %} \
        {{ 1 + index - dock_apps | length }} \
        {% else %} \
        {{ index + 1 }} \
        {% endif %} \
        --no-restart {{ item.options | default() }} && \
      echo changed \
    )
  loop: "{{ dock_apps + dock_dirs }}"
  loop_control:
    index_var: index
  register: dock_change
  changed_when: '"changed" in dock_change.stdout'
  notify: restart dock


## ----------------------------
## Settings accessible from CLI
## ----------------------------
#TODO: this needs testing
- name: set plist defaults
  tags: plist
  osx_defaults:
    state: present
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  loop: "{{ osx_defaults }}"
  notify: restart mac services
  when: no
