---
## ---------------------------------------
## Install python packages and virtualenvs
## ---------------------------------------
- name: install python packages (global)
  tags: python
  pip:
    name: "{{ item }}"
  with_items: "{{ python_global_packages }}"
