alias ls='ls -F' # show symbols for file types
alias ll='ls -lh' # show long format with human readable sizes
alias lla='ll -A' # show long format with hidden files
alias la='ls -A' # show all files
alias l1='ls -1' # show in one column
alias vimp='vim -p' # tab for each file
alias vimo='vim -O' # vertical split
alias free='free -h' # always human readable format
alias grep='grep --color=auto' # always output colour
alias tree='tree --du -h -C --dirsfirst' # show size and colour

# the fuck setup probably should go in bashrc or other
eval `thefuck --alias`
alias f='fuck'
