" required for Vundle
set nocompatible    " don't worry about compatibility



"---------------------------------- PLUGINS -----------------------------------"
call plug#begin('~/.vim/plugged')
    Plug 'junegunn/vim-plug'

    " extra languages
    Plug 'chr4/nginx.vim'
    Plug 'derekwyatt/vim-scala'
    Plug 'leafgarland/typescript-vim'
    Plug 'mxw/vim-jsx'
    Plug 'pangloss/vim-javascript'
    Plug 'pearofducks/ansible-vim'
    Plug 'scrooloose/syntastic'

    " themes
    Plug 'airblade/vim-gitgutter'
    Plug 'chriskempson/base16-vim'
    Plug 'mhinz/vim-signify'
    Plug 'paranoida/vim-airlineish'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    " navigating
    Plug 'junegunn/fzf.vim'
    Plug 'majutsushi/tagbar'
    Plug 'scrooloose/nerdcommenter'
    Plug 'scrooloose/nerdtree'
    Plug 'wesQ3/vim-windowswap'
    Plug 'xolox/vim-easytags'
    Plug 'xolox/vim-misc'
    Plug 'Xuyuanp/nerdtree-git-plugin'

    " syntax/linting
    Plug 'editorconfig/editorconfig-vim'
    " Plug 'w0rp/ale'

    " completion
    Plug 'honza/vim-snippets'
    Plug 'KabbAmine/zeavim.vim'
    Plug 'sirver/ultisnips'
    " Plug 'valloric/youcompleteme'

    " other utils
    Plug 'itchyny/calendar.vim'
    Plug 'sjl/gundo.vim'
    Plug 'terryma/vim-multiple-cursors'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-obsession'
    Plug 'tpope/vim-ragtag'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-speeddating'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-unimpaired'
    " Plug 'skwp/greplace.vim'
    Plug 'wakatime/vim-wakatime'
call plug#end()



"---------------------------------- COLOURS -----------------------------------"
" don't fail if colorscheme not found
silent! colorscheme base16-solarflare
highlight Comment cterm=italic  " enable italics for comments
set termguicolors



set number relativenumber       " display relative and normal line numbers
set mouse=a                     " enable mouse for all modes
set expandtab                   " expand tabs to spaces
set smarttab                    " delete 'shiftwidth' spaces at a time
set smartindent                 " add tabs by default
set autoindent                  " automatically indent
set tabstop=4                   " number of spaces of <Tab>
set shiftwidth=4                " number of spaces of indent
set shiftround                  " round indents to nearest `shiftwidth`
set listchars+=tab:»\ ,trail:▫,eol:¬,space:·    " invisible characters
" set list                        " show invisibles
set foldmethod=indent           " fold with equal indents
set foldlevel=99                " leave all folds open by default
set autowriteall                " write contents when switching away

set scrolloff=5                 " show 5 context lines when scrolling
set sidescroll=1                " use continuous scrolling
set sidescrolloff=10            " show 10 context columns when scrolling
set nowrap                      " do not wrap lines by default
set colorcolumn=121             " vertical line at column 121

set hlsearch                    " highlight search matches
set incsearch                   " show incremental matches
set ignorecase                  " ignore case by default
set smartcase                   " include case if present

set t_Co=256                    " set terminal to 256 colours
set cursorline                  " highlight current line
"set cursorcolumn                " higlight current column
set laststatus=2                " always show the status line
set backspace=indent,start,eol  " backspace over everything

set showcmd                     " show command line
set wildmenu                    " show command completion matches
set wildignore=*.swp,*.pyc,*.o  " ignore files when expanding wildcards
set autoread                    " automatically update external changes
" set clipboard=unnamed,unnamedplus       " share system clipboard

set splitbelow                  " but the new window below
set splitright                  " put the new window to the right

set formatoptions+=ojr          " insert comment leader when using 'o' or 'O'
                                " insert comment leader on <Enter>
                                " remove comment leader when joining lines
set pastetoggle=<F2>            " key to toggle paste mode



"---------------------------------- MAPPINGS ----------------------------------"
" change <Leader> to ','
let mapleader=','
" save pressing shift
nmap ; :
" shortcut to edit vimrc file
nmap <Leader>ev :tabedit $MYVIMRC<cr>
" shortcut to edit i3 config
nmap <Leader>ei :tabedit $HOME/.config/i3/config<cr>
" shortcut to edit Zsh config
nmap <Leader>ez :tabedit $HOME/.zshrc<cr>
" remove highlighted search
nmap <Leader><space> :nohlsearch<cr>
" fzf map
nnoremap <silent> <C-P> :Files<cr>
nnoremap <silent> <C-B> :Buffers<cr>
nnoremap <silent> <C-M> :Marks<cr>
nnoremap <silent> <leader>t :BTags<cr>
nnoremap <silent> <leader>gl :Commits<CR>
nnoremap <silent> <leader>ga :BCommits<CR>
" shortcuts for tab/buffer navigation
nnoremap <silent> <leader>n :bprev<cr>
nnoremap <silent> <leader>m :bnext<cr>

" easier split movements
nmap <C-H> <C-W><C-H>
nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-L> <C-W><C-L>

" bind K to grep word under cursor using fzf
nnoremap <silent> K :execute 'Rg' expand('<cword>')<CR>

" toggle nerdtree
nmap <C-\> :NERDTreeToggle<cr>

" toggle tag viewer
nnoremap <Leader>tt :TagbarToggle<cr>

" use space to toggle folding
nnoremap <space> za
" search for word under cursor
nnoremap // yiw/<C-R>"<CR>

" vim-fugitive
map <Leader>gs :Gstatus<CR>
map <Leader>gd :Gdiff<CR>
map <Leader>gc :Gcommit<CR>
map <Leader>gw :Gwrite<CR>
map <Leader>gp :Gpush<CR>



"------------------------------- AUTO COMMANDS --------------------------------"
" augroup autosourcing
"     " clear the group
"     autocmd!
"     " source vimrc when it changes
"     autocmd BufWritePost $MYVIMRC source $MYVIMRC
" augroup END



"------------------------------ PLUGIN CONFIGS --------------------------------"
" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#buffer_nr_show = 0
let g:airline#extensions#tabline#buffer_min_count = 0
let g:airline#extensions#tabline#tab_min_count = 2

" ultisnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-b>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"

" calendar
let g:calendar_google_calendar = 1
let g:calendar_google_task = 1
let g:calendar_task = 1

" fzf
let g:fzf_layout = {'down': '15'} " number of results to show
let g:fzf_buffers_jump = 1  " jump to open buffer if possible

" use rg for grep
if executable('rg')
    set grepprg=rg\ --vimgrep
    set grepformat^=%f:%l:%c:%m
endif

" NERDTree
let NERDTreeHijackNetrw = 0

" NERDCommenter
let NERDCommentEmptyLines = 1
let NERDRemoveExtraSpaces = 1
let NERDSpaceDelims = 1
let NERDDefaultAlign = 'left'

" ansible-vim
let g:ansible_name_highlight = 'b'
let g:ansible_extra_keywords_highlight = 1

" vim-jsx
let g:jsx_ext_required = 0

" KabbAmine/zeavim.vim
let g:zv_file_types = {
    \ 'php' : 'php,laravel,phpunit,yii,doctrine'
    \ }
