" required for Vundle
set nocompatible    " don't worry about compatibility
filetype off        " disable filetype detection



"---------------------------------- PLUGINS -----------------------------------"
" append Vundle to the runtime path
set rtp+=~/.vim/bundle/Vundle.vim
" initialise Vundle
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'

    " extra languages
    Plugin 'chr4/nginx.vim'
    Plugin 'derekwyatt/vim-scala'
    Plugin 'leafgarland/typescript-vim'
    Plugin 'mxw/vim-jsx'
    Plugin 'pangloss/vim-javascript'
    Plugin 'pearofducks/ansible-vim'
    Plugin 'scrooloose/syntastic'
    " Plugin 'elzr/vim-json'
    " Plugin 'sudar/vim-arduino-syntax'

    " themes
    Plugin 'airblade/vim-gitgutter'
    Plugin 'chriskempson/base16-vim'
    Plugin 'mhinz/vim-signify'
    Plugin 'paranoida/vim-airlineish'
    Plugin 'vim-airline/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'

    " navigating
    Plugin 'junegunn/fzf.vim'
    Plugin 'majutsushi/tagbar'
    Plugin 'scrooloose/nerdcommenter'
    Plugin 'scrooloose/nerdtree'
    " Plugin 'vim-scripts/a.vim'
    Plugin 'wesQ3/vim-windowswap'
    Plugin 'xolox/vim-easytags'
    Plugin 'xolox/vim-misc'
    Plugin 'Xuyuanp/nerdtree-git-plugin'

    " syntax/linting
    Plugin 'editorconfig/editorconfig-vim'
    " Plugin 'w0rp/ale'

    " completion
    Plugin 'honza/vim-snippets'
    Plugin 'KabbAmine/zeavim.vim'
    Plugin 'sirver/ultisnips'
    " Plugin 'valloric/youcompleteme'

    " other utils
    Plugin 'sjl/gundo.vim'
    Plugin 'terryma/vim-multiple-cursors'
    Plugin 'tpope/vim-fugitive'
    Plugin 'tpope/vim-obsession'
    Plugin 'tpope/vim-ragtag'
    Plugin 'tpope/vim-repeat'
    Plugin 'tpope/vim-speeddating'
    Plugin 'tpope/vim-surround'
    Plugin 'tpope/vim-unimpaired'
    " Plugin 'skwp/greplace.vim'
    Plugin 'wakatime/vim-wakatime'
call vundle#end()

filetype plugin indent on       " re-enable filetype detection



"---------------------------------- COLOURS -----------------------------------"
syntax on                       " enable syntax highlighting
" don't fail if colorscheme not found
silent! colorscheme base16-solarflare
highlight Comment cterm=italic  " enable italics for comments
set termguicolors



set number relativenumber       " display relative and normal line numbers
set mouse=a                     " enable mouse for all modes
set expandtab                   " expand tabs to spaces
set smarttab                    " delete 'shiftwidth' spaces at a time
set smartindent                 " add tabs by default
set autoindent                  " automatically indent
set tabstop=4                   " number of spaces of <Tab>
set shiftwidth=4                " number of spaces of indent
set shiftround                  " round indents to nearest `shiftwidth`
set listchars+=tab:»\ ,trail:▫,eol:¬,space:·    " invisible characters
" set list                        " show invisibles
set foldmethod=indent           " fold with equal indents
set foldlevel=99                " leave all folds open by default
set autowriteall                " write contents when switching away

set scrolloff=5                 " show 5 context lines when scrolling
set sidescroll=1                " use continuous scrolling
set sidescrolloff=10            " show 10 context columns when scrolling
set nowrap                      " do not wrap lines by default
set colorcolumn=121             " vertical line at column 121

set hlsearch                    " highlight search matches
set incsearch                   " show incremental matches
set ignorecase                  " ignore case by default
set smartcase                   " include case if present

set t_Co=256                    " set terminal to 256 colours
set cursorline                  " highlight current line
"set cursorcolumn                " higlight current column
set laststatus=2                " always show the status line
set backspace=indent,start,eol  " backspace over everything

set showcmd                     " show command line
set wildmenu                    " show command completion matches
set wildignore=*.swp,*.pyc,*.o  " ignore files when expanding wildcards
set autoread                    " automatically update external changes
" set clipboard=unnamed,unnamedplus       " share system clipboard

set splitbelow                  " but the new window below
set splitright                  " put the new window to the right

set formatoptions+=ojr          " insert comment leader when using 'o' or 'O'
                                " insert comment leader on <Enter>
                                " remove comment leader when joining lines
set pastetoggle=<F2>            " key to toggle paste mode



"---------------------------------- MAPPINGS ----------------------------------"
" change <Leader> to ','
let mapleader=','
" save pressing shift
nmap ; :
" shortcut to edit vimrc file
nmap <Leader>ev :tabedit $MYVIMRC<cr>
" shortcut to edit i3 config
nmap <Leader>ei :tabedit $HOME/.config/i3/config<cr>
" shortcut to edit Zsh config
nmap <Leader>ez :tabedit $HOME/.zshrc<cr>
" remove highlighted search
nmap <Leader><space> :nohlsearch<cr>
" fzf map
nnoremap <silent> <C-P> :Files<cr>
nnoremap <silent> <C-B> :Buffers<cr>
nnoremap <silent> <leader>m :Marks<cr>
nnoremap <silent> <leader>t :BTags<cr>
nnoremap <silent> <leader>gl :Commits<CR>
nnoremap <silent> <leader>ga :BCommits<CR>

" easier split movements
nmap <C-H> <C-W><C-H>
nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-L> <C-W><C-L>

" bind K to grep word under cursor using fzf
nnoremap <silent> K :execute 'Rg' expand('<cword>')<CR>

" toggle nerdtree
nmap <C-\> :NERDTreeToggle<cr>

" toggle tag viewer
nnoremap <Leader>tt :TagbarToggle<cr>

" use space to toggle folding
nnoremap <space> za
" search for word under cursor
nnoremap // yiw/<C-R>"<CR>

" vim-fugitive
map <Leader>gs :Gstatus<CR>
map <Leader>gd :Gdiff<CR>
map <Leader>gc :Gcommit<CR>
map <Leader>gw :Gwrite<CR>
map <Leader>gp :Gpush<CR>



"------------------------------- AUTO COMMANDS --------------------------------"
" augroup autosourcing
"     " clear the group
"     autocmd!
"     " source vimrc when it changes
"     autocmd BufWritePost $MYVIMRC source $MYVIMRC
" augroup END



"------------------------------ PLUGIN CONFIGS --------------------------------"
" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" let g:airline_theme = 'onedark'
let g:airline#extensions#tabline#buffer_idx_mode = 1
" let g:airline#extensions#tabline#left_sep = ''
" let g:airline#extensions#tabline#left_alt_sep = ''
" let g:airline#extensions#tabline#right_sep = ''
" let g:airline#extensions#tabline#right_alt_sep = ''
" shortcuts for tab/buffer navigation
nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9
nmap <leader>n <Plug>AirlineSelectPrevTab
nmap <leader>m <Plug>AirlineSelectNextTab
let g:airline#extensions#tabline#buffer_nr_show = 0
let g:airline#extensions#tabline#buffer_min_count = 2
let g:airline#extensions#tabline#tab_min_count = 2

" ultisnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<c-b>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"

" vim-signify/vim-gitgutter
" let g:signify_line_highlight = 1
" let g:gitgutter_highlight_lines = 1

" fzf
let g:fzf_layout = {'down': '15'} " number of results to show
let g:fzf_buffers_jump = 1  " jump to open buffer if possible

" use rg for grep
if executable('rg')
    set grepprg=rg\ --vimgrep
    set grepformat^=%f:%l:%c:%m
endif

" NERDTree
let NERDTreeHijackNetrw = 0

" NERDCommenter
let NERDCommentEmptyLines = 1
let NERDRemoveExtraSpaces = 1
let NERDSpaceDelims = 1
let NERDDefaultAlign = 'left'

" ansible-vim
let g:ansible_name_highlight = 'b'
let g:ansible_extra_keywords_highlight = 1

" vim-jsx
let g:jsx_ext_required = 0

" KabbAmine/zeavim.vim
let g:zv_file_types = {
    \ 'php' : 'php,laravel,phpunit,yii,doctrine'
    \ }
