---
## ------------------------------------------
## AWS CLI profile settings (vault protected)
## ------------------------------------------
aws_profiles: "{{ vault_aws_profiles }}"

aws_config: "{{ vault_aws_config }}"
