---
## ---------------------
## Files to download
## ---------------------
download_files:
  - url: https://raw.githubusercontent.com/99designs/aws-vault/master/contrib/completions/zsh/aws-vault.zsh
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/aws-vault/aws-vault.plugin.zsh"
