---
## ---------------------
## Custom repos to clone
## ---------------------
git_repos:
  - url: git@github.com:jradtilbrook/oh-my-zsh.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
  - url: git@github.com:jradtilbrook/bitwarden-rofi.git
    dest: "{{ ansible_user_dir }}/projects/bitwarden-rofi"
  - url: git@github.com:blimmer/zsh-aws-vault.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-aws-vault"
    # this is pretty hacky but works for now. if/when custom autoload scripts are added, it wont work
  - url: git@github.com:junegunn/vim-plug.git
    dest: "{{ ansible_user_dir }}/.vim/autoload" # this is pretty hacky
  - url: https://aur.archlinux.org/yay.git
    dest: "{{ ansible_user_dir }}/projects/yay"
  - "{{ vault_git_repos }}"
