---
## ----
## Dock
## ----
dock_items:
  - name: /Applications/Google Chrome.app
  - name: /Applications/Firefox Developer Edition.app
  - name: /Applications/Safari.app
  - name: /Applications/iTunes.app
  - name: /Applications/Spotify.app
  - name: /Applications/Notes.app
  - name: /Applications/Atom.app
  - name: /Applications/iTerm.app
  - name: /Applications/Slack.app
  - name: /Applications/Insomnia.app
  - name: /Applications/PhpStorm.app
  - name: /Applications/System Preferences.app
  # folder positions are relative to folders section on the dock
  # the options key is required for folders
  - name: ~/Downloads
    options: --display folder --sort name --view auto --section others
  - name: ~/Documents
    options: --display folder --sort name --view auto --section others
