---
## ---------------------
## OSX defaults settings
## ---------------------
# the above commands need to restart some/all of these services
# Finder, Dock, Safari and maybe SystemUIServer, cfprefsd
osx_defaults:
  # allow tab in modal dialogs (space to select)
  - domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
  # subpixel font rendering on non-apple displays
  - domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 2
  # autohide dock
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  # show dock on left
  - domain: com.apple.dock
    key: orientation
    type: string
    value: left
  # dock icon size
  - domain: com.apple.dock
    key: tilesize
    type: int
    value: 30
  - domain: com.apple.dock
    key: largesize
    type: int
    value: 45
  # translucent hidden apps
  - domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
  # show file extensions
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  # show path bar in finder
  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
  # show status bar in finder
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  # expand save panel
  - domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  # expand print panel
  - domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  # use key repeat no press-and-hold
  - domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  # enable tap to click
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true
  # enable Safari's debug/dev menu
  - domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: bool
    value: true
  - domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true
  # mission control group by app
  - domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: true
  # disable automatic substitution of quotes and dashes
  - domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  - domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  # fast key repeat
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 20
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
  # save screenshots to desktop
  - domain: com.apple.screencapture
    key: location
    type: string
    value: ${HOME}/Desktop
  # screenshots in PNG
  - domain: com.apple.screencapture
    key: type
    type: string
    value: png
  # allow selection in quick look
  - domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true
  # show hard drives, servers and removable media on desktop
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
  # - defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true
  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
  # automatically open a new Finder window when a volume is mounted
  - domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true
  - domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true
  - domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true
  # show all finder windows in list view
  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: clmv
  # highlight in pink
  - domain: NSGlobalDomain
    key: AppleHighlightColor
    type: string
    value: 1.000000 0.749020 0.823529
  # natural scrolling
  - domain: -g
    key: com.apple.swipescrolldirection
    type: bool
    value: true

## --------------
## Plist settings
## --------------
# these arent done automatically yet, just put here for documentation purposes.
# TODO: try to add a task for them
mac_plist_settings:
  # enable snap-to-grid for icons on the desktop and in other icon views
  - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  - /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  # set the size of icons on the desktop and in other icon views
  - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 52" ~/Library/Preferences/com.apple.finder.plist
  - /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 52" ~/Library/Preferences/com.apple.finder.plist
  - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 52" ~/Library/Preferences/com.apple.finder.plist
  # show Library folder
  - chflags nohidden ~/Library
