#!/usr/bin/env bash

# capture current bluetooth controller/adapter power state
POWER=$(bluetoothctl show | sed -n "s/.*Powered:.*\(yes\).*/On/pI")
[ -z $POWER ] && POWER="Off"
# capture headphones connection status
DEVICE=$(bluetoothctl info | sed -n "s/.*Name:\s\+\(.*\)/\1/pI")
[ -z "$DEVICE" ] && DEVICE="Disconnected"

# respond to a click event
case $BLOCK_BUTTON in
    1) # left click = connect/disconnect
        [ $POWER = "Off" ] && bluetoothctl power on >/dev/null
        ~/.local/bin/bluetooth.sh connect
    ;;
    2) # middle click - power on/off
        if [ $POWER = "On" ]; then
            SET_POWER=off
        else
            SET_POWER=on
        fi
        bluetoothctl power $SET_POWER >/dev/null
    ;;
    3) # right click = disconnect
        [ $POWER = "Off" ] && break
        ~/.local/bin/bluetooth.sh disconnect
    ;;
esac

# print the output for the current state
if [ $POWER = "Off" ]; then
    echo $POWER
else
    if [ "$DEVICE" = "Disconnected" ]; then
        COLOUR='#E4B51C'
    else
        COLOUR='#33B5E1'
    fi

    echo $DEVICE
    echo $DEVICE
    echo $COLOUR
fi
