[[session]]
name = "dotfiles"
path = "~/developer/dotfiles/"

[[session]]
name = "megatron"
path = "~/developer/he/megatron/"

[[session]]
name = "k8s"
path = "~/developer/he/k8s/"
startup_command = "export AWS_PROFILE=hedev"
