#!/bin/sh
#
# Invoked when git-checkout or git-switch is run, after having updated the worktree.
# $1 = ref of previous HEAD
# $2 = ref of new HEAD
# $3 = 1 for branch change, 0 for file checkout
# Also runs after git-clone where $1 is the null ref, $2 is the new HEAD and $3 is 1
#
# To enable this hook, put it in the .git/hooks directory.
#

#
# Check for a composer.lock file and run composer install in a new terminal
# Check for a yarn.lock file and run yarn in a new terminal
#

#
# NOTE:
# This has the potential to spawn infinite terminals if composer or yarn install dependencies from git that have these
# files which recursively have other dependencies
#

shopt -s extglob

if [ $1 = 0000000000000000000000000000000000000000 ]; then # if its a fresh clone with null ref
    # try run updates regardless of checking changes
    $(dirname $0)/update-composer
    $(dirname $0)/update-yarn
elif [ $3 -eq 1 ]; then # if we are changing branches
    # only update if changed
    if ! git diff-tree -r --quiet $1 $2 -- composer.lock yarn.lock; then
        $(dirname $0)/update-composer
        $(dirname $0)/update-yarn
    fi
fi
