#!/bin/sh
#
# Invoked when git-checkout or git-switch is run, after having updated the worktree.
# $1 = ref of previous HEAD
# $2 = ref of new HEAD
# $3 = 1 for branch change, 0 for file checkout
# Also runs after git-clone where $1 is the null ref, $2 is the new HEAD and $3 is 1
#
# To enable this hook, put it in the .git/hooks directory.

# Check for a composer.lock file and run composer install in a new terminal
# Check for a yarn.lock file and run yarn in a new terminal
#

shopt -s extglob

# if we are changing branches
if [ $3 -eq 1 ]; then
    [ -f composer.lock ] && git diff --quiet $1 $2 -- composer.lock || i3-sensible-terminal -r scratch -d $(pwd) --hold -e 'composer install' 2&>1 >/dev/null &
    [ -f yarn.lock ] && git diff --quiet $1 $2 -- yarn.lock || i3-sensible-terminal -r scratch -d $(pwd) --hold -e 'yarn' 2&>1 >/dev/null &
fi
