#!/bin/sh
#
# Invoked when git-merge is run.
# $1 = flag specifying whether or not the merge being done was a squash merge
#
# To enable this hook, put it in the .git/hooks directory.
#

#
# Check for a composer.lock file and run composer install in a new terminal
# Check for a yarn.lock file and run yarn in a new terminal
#
exit

shopt -s extglob

if ! git diff-tree -r --quiet HEAD@{0} HEAD@{1} -- composer.lock package-lock.json yarn.lock; then
    ~/.git-templates/hooks/update-composer
    ~/.git-templates/hooks/update-node
fi
