---
## ---------------------------
## Arch Linux systemd services
## ---------------------------
system_services:
  - bluetooth.service
  - docker.socket # starts docker on demand when first trying to use it
  # - i3lock.service # this can't be here because it is also _started_ which is annoying
  - systemd-networkd.service
  - systemd-resolved.service
  - systemd-timesyncd.service
  - tmp-hostpath\x2dprovisioner.mount
  - ufw.service
  - wpa_supplicant@wlp1s0.service

user_services:
  - greenclip.service
  # - mpd.service # this is not enabled because it conflicts with mopidy
  - redshift.service
