---
## ---------------------------
## Arch Linux systemd services
## ---------------------------
system_services:
  - bluetooth.service
  - docker.socket # starts docker on demand when first trying to use it
  - ufw.service

user_services:
  - redshift.service
  # - mpd.service # this is not enabled because it conflicts with mopidy
